[package]
edition = "2021"
name = "oxc-jsx-dom-expressions"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"
oxc = { version = "0.31.0", features = ["parser", "transformer", "codegen", "sourcemap"] }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
